// DO NOT EDIT: file generated by protoc-gen-pgx
package pgxpb

import "github.com/jackc/pgx/v5/pgxpool"
import "github.com/jackc/pgx/v5"
import "context"
import "fmt"

type PersonsRepository struct {
	pool *pgxpool.Pool
}

func NewPersonsRepository(pool *pgxpool.Pool) *PersonsRepository {
	return &PersonsRepository{
		pool: pool,
	}
}

type Person struct {
	name string
}

const insertQuery = `
INSERT INTO persons 
(name)
VALUES 
(@name)
`

func (repo *PersonsRepository) InsertPerson(ctx context.Context, person Person) error {
	conn, err := repo.pool.Acquire(ctx)
	if err != nil {
		return err
	}
	defer conn.Release()

	args := pgx.NamedArgs{
		"name": person.name,
	}

	if _, err := conn.Exec(ctx, insertQuery, args); err != nil {
		return fmt.Errorf("failed to insert data into persons table: %w", err)
	}

	return nil
}
