// DO NOT EDIT: file generated by protoc-gen-pgx
package pb

import "github.com/jackc/pgx/v5/pgxpool"
import "github.com/jackc/pgx/v5"
import "context"
import "fmt"

type TestersRepository struct {
	pool *pgxpool.Pool
}

func NewTestersRepository(pool *pgxpool.Pool) *TestersRepository {
	return &TestersRepository{
		pool: pool,
	}
}

type Testers struct {
	kale string
	tt   int64
}

const insertQuery = `
INSERT INTO testers 
(kale,tt)
VALUES 
(@kale, @tt)
`

func (repo *TestersRepository) InsertTesters(ctx context.Context, testers Testers) error {
	conn, err := repo.pool.Acquire(ctx)
	if err != nil {
		return err
	}
	defer conn.Release()

	args := pgx.NamedArgs{
		"kale": testers.kale,
		"tt":   testers.tt,
	}

	if _, err := conn.Exec(ctx, insertQuery, args); err != nil {
		return fmt.Errorf("failed to insert data into testers table: %w", err)
	}

	return nil
}
